title: Mohamed ElSalmi # your name (or website title) here
logo: "/images/git\ avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Master's candidate at Harvard University in Data Science. This is my online portfolio 
  which I update regularly with projects that I am working on. 
  <br><br>
  <a href="https://www.linkedin.com/in/mohamed-elsalmi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
